# Generated by Django 5.2 on 2025-09-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imageitem_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageitems', to='images.image'),
        ),
    ]
