# Generated by Django 5.0.14 on 2026-08-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('url', models.CharField(help_text="Renseigner sous la forme DOMAINE/SOUS-DOMAINE sans '/' à la fin.", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
            },
        ),
        migrations.CreateModel(
            name='UserIAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaines', models.ManyToManyField(blank=True, related_name='droits', to='core.domain', verbose_name='Domaines autorisés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authenticate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Droit Utilisateur',
                'verbose_name_plural': 'Droits Utilisateur',
            },
        ),
    ]
