server {
    listen 880;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA React / Vite
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Fichiers statiques (images, js, css…) déjà inclus via root

    client_max_body_size 10M;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;
}
