FROM python:3.12-slim AS prod

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 

COPY Authenticate /app/Authenticate


WORKDIR /app/Authenticate

RUN apt-get update && apt-get install -y \
    build-essential \
    libmariadb-dev-compat \
    libmariadb-dev \
    pkg-config \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


COPY django_tags_app-0.1.0-py3-none-any.whl /tmp/django_tags_app-0.1.0-py3-none-any.whl

RUN set -euo pipefail \
    && pip install --no-cache-dir -r requirement.in \
    && pip install --no-cache-dir /tmp/django_tags_app-0.1.0-py3-none-any.whl \
    && rm -f /tmp/django_tags_app-0.1.0-py3-none-any.whl \
    && find /app -type d -name "__pycache__" -exec rm -rf {} +

COPY prodentrypoint.sh /app/prodentrypoint.sh
RUN chmod +x /app/prodentrypoint.sh
EXPOSE 5190

ENTRYPOINT ["/app/prodentrypoint.sh"]
