
FROM python:3.12-slim AS dev

ENV PYTHONUNBUFFERED=1 PIP_ROOT_USER_ACTION=ignore PYTHONDONTWRITEBYTECODE=1


# Outils nécessaires pour télécharger l'asset privé
RUN apt-get update && apt-get install -y --no-install-recommends curl && apt-get install -y nano \
    && rm -rf /var/lib/apt/lists/*\
    && apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config

COPY Authenticate /app/Authenticate

WORKDIR /app/Authenticate

COPY django_tags_app-0.1.0-py3-none-any.whl /tmp/django_tags_app-0.1.0-py3-none-any.whl
COPY django_users_apps-0.1.1-py3-none-any.whl /tmp/django_users_apps-0.1.1-py3-none-any.whl

RUN set -euo pipefail \
    && pip install --no-cache-dir -r /app/Authenticate/requirement.in \
    && pip install --no-cache-dir /tmp/django_tags_app-0.1.0-py3-none-any.whl \
    && pip install --no-cache-dir /tmp/django_users_apps-0.1.1-py3-none-any.whl \
    && rm -f /tmp/django_tags_app-0.1.0-py3-none-any.whl \
    && rm -f /tmp/django_users_apps-0.1.1-py3-none-any.whl \
    && find /app -type d -name "__pycache__" -exec rm -rf {} +

# Dossier des logs (si nécessaire)
RUN mkdir -p /app/save
EXPOSE 5190 

VOLUME ["/app/save"]

# Django : bind sur 0.0.0.0 et log du jour
#CMD ["bash","-lc","python manage.py runserver 0.0.0.0:PORT | tee -a ./save/$(date +'%Y-%m-%d')_trace.log"]
CMD ["bash","-lc","python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:5190 | tee -a ./save/$(date +'%Y-%m-%d')_trace.log"]

