# Generated by Django 5.2 on 2025-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage"),
        ),
    ]
