# Generated by Django 6.0.3 on 2026-04-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChakraTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('chakra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Modèle d’UI',
                'verbose_name_plural': 'Modèles d’UI',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Modèle d’email',
                'verbose_name_plural': 'Modèles d’email',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur peut se connecter au site d’administration de la plateforme.", verbose_name="Membre"),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indique que cet utilisateur a tous les droits', verbose_name='Administrateur Plateforme'),
        ),
        migrations.CreateModel(
            name='WebConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('config', models.JSONField(verbose_name='configuration')),
                ('ui_template', models.ForeignKey(blank=True, help_text='Modèle d’interface utilisateur à utiliser pour cette application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_templates', to='core.chakratemplate', verbose_name='Modèle d’UI')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='config',
            field=models.ForeignKey(blank=True, help_text="Preciser le profil d'application à utiliser pour cet utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.webconfig', verbose_name='parametrage'),
        ),
    ]
