# Generated by Django 6.0.3 on 2026-04-07 12:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chakratemplate_emailtemplate_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webconfig',
            name='config',
            field=models.JSONField(default=core.models.get_default_config, verbose_name='configuration'),
        ),
    ]
