# Generated by Django 6.0.5 on 2026-05-28 14:44

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_webconfig_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_creation', models.DateField(default=datetime.date.today, help_text='Format dd/mm/yyyy', verbose_name='Date de création')),
                ('horodatage_creation', models.TimeField(auto_now_add=True, help_text='Format HH:MM', verbose_name='Heure de création')),
                ('chemin', models.TextField(verbose_name='Chemin système')),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
                'ordering': ['nom'],
            },
        ),
    ]
