# Generated by Django 6.0.5 on 2026-05-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fichier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichier',
            options={'ordering': ['date_creation'], 'verbose_name': 'Fichier', 'verbose_name_plural': 'Fichiers'},
        ),
        migrations.AddField(
            model_name='fichier',
            name='chemin_destinataire',
            field=models.TextField(blank=True, null=True, verbose_name='Chemin système chez le client'),
        ),
        migrations.AddField(
            model_name='fichier',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur déposant'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
